### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by deanmorin** [maljub01/rbenv-bundle-exec#2]
I'd like to add a Homebrew formula for this plugin, but it doesn't have a release to link against.

For example, I would need something like:

```
url 'https://github.com/maljub01/rbenv-bundle-exec/archive/v1.0.0.tar.gz'
```

Currently there is only HEAD to link against:

```
url 'https://github.com/maljub01/rbenv-bundle-exec/archive/master.zip'
```

Homebrew requires a stable tarball for standard formulae.

**Comment by maljub01** [comment]
Hi @deanmorin,

Thanks for opening this issue. I have created a release and the Homebrew formula should work now. I will maintain releases for any future updates using [semantic versioning](http://semver.org/).

**Comment by deanmorin** [comment]
Good stuff, I created a pull request so it should be available in Homebrew soon.

https://github.com/Homebrew/homebrew/pull/32408
